version: "3.8"
services:
  app:
    container_name: my-node-app
    image: my-node-app
    ports:
      - 3010:5000
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
